import altair as alt
import streamlit as st

from penn_chime.presentation import (
    additional_projections_chart,
    admitted_patients_chart,
    display_header,
    display_sidebar,
    display_n_days_slider,
    draw_census_table,
    draw_projected_admissions_table,
    draw_raw_sir_simulation_table,
    hide_menu_style,
    new_admissions_chart,
    show_additional_projections,
    show_more_info_about_this_tool,
    write_definitions,
    write_footer,
)
from penn_chime.utils import build_admissions_df, build_census_df
from penn_chime.settings import DEFAULTS


# This is somewhat dangerous:
# Hide the main menu with "Rerun", "run on Save", "clear cache", and "record a screencast"
# This should not be hidden in prod, but removed
# In dev, this should be shown
st.markdown(hide_menu_style, unsafe_allow_html=True)

p = display_sidebar(st, DEFAULTS)

display_header(
    st,
    total_infections=p.infected,
    initial_infections=p.known_infected,
    detection_prob=p.detection_probability,
    current_hosp=p.current_hospitalized,
    hosp_rate=p.hospitalized.rate,
    S=p.susceptible,
    market_share=p.market_share,
    recovery_days=p.recovery_days,
    r_naught=p.r_naught,
    doubling_time=p.doubling_time,
    relative_contact_rate=p.relative_contact_rate,
    r_t=p.r_t,
    doubling_time_t=p.doubling_time_t,
)
if st.checkbox("Show more info about this tool"):
    notes = "The total size of the susceptible population will be the entire catchment area for Penn Medicine entities (HUP, PAH, PMC, CCH)"
    show_more_info_about_this_tool(
        st=st,
        recovery_days=p.recovery_days,
        doubling_time=p.doubling_time,
        r_naught=p.r_naught,
        relative_contact_rate=p.relative_contact_rate,
        doubling_time_t=p.doubling_time_t,
        r_t=p.r_t,
        inputs=DEFAULTS,
        notes=notes

    )

display_n_days_slider(st, p, DEFAULTS)

# begin format data
projection_admits = build_admissions_df(p.n_days, *p.dispositions)
census_df = build_census_df(projection_admits, *p.lengths_of_stay)
# end format data

st.subheader("New Admissions")
st.markdown("Projected number of **daily** COVID-19 admissions at Penn hospitals")
st.altair_chart(
    new_admissions_chart(alt, projection_admits, p.n_days - 10), use_container_width=True,
)
if st.checkbox("Show Projected Admissions in tabular form"):
    draw_projected_admissions_table(st, projection_admits)
st.subheader("Admitted Patients (Census)")
st.markdown(
    "Projected **census** of COVID-19 patients, accounting for arrivals and discharges at Penn hospitals"
)
st.altair_chart(admitted_patients_chart(alt, census_df, p.n_days - 10), use_container_width=True)
if st.checkbox("Show Projected Census in tabular form"):
    draw_census_table(st, census_df)
st.markdown(
    """**Click the checkbox below to view additional data generated by this simulation**"""
)
if st.checkbox("Show Additional Projections"):
    show_additional_projections(st, alt, additional_projections_chart, p.infected_v, p.recovered_v)
    if st.checkbox("Show Raw SIR Simulation Data"):
        draw_raw_sir_simulation_table(st, p.n_days, p.susceptible_v, p.infected_v, p.recovered_v)
write_definitions(st)
write_footer(st)
