FROM python:3.7.7-slim-buster

COPY .streamlit ~/

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -q -r requirements.txt

COPY . .

ARG PORT

EXPOSE $PORT 

CMD gunicorn src.dash_app:server --bind 0.0.0.0:$PORT
