FROM python:3.7.7-slim-buster

COPY ./requirements.txt /code/requirements.txt

WORKDIR code

RUN pip install -q -r requirements.txt

COPY src src 

EXPOSE $PORT 

CMD gunicorn src.dash_app:server --bind 0.0.0.0:$PORT
