"""App."""

import altair as alt  # type: ignore
import streamlit as st  # type: ignore

from penn_chime.presentation import (
    display_download_link,
    display_header,
    display_sidebar,
    draw_raw_sir_simulation_table,
    hide_menu_style,
    show_additional_projections,
    show_more_info_about_this_tool,
    write_definitions,
    write_footer,
)
from penn_chime.settings import DEFAULTS
from penn_chime.models import SimSirModel
from penn_chime.charts import (
    build_admits_chart,
    build_admits_table,
    build_census_chart,
    build_census_table,
    additional_projections_chart,
    chart_descriptions
)

# This is somewhat dangerous:
# Hide the main menu with "Rerun", "run on Save", "clear cache", and "record a screencast"
# This should not be hidden in prod, but removed
# In dev, this should be shown
st.markdown(hide_menu_style, unsafe_allow_html=True)

p = display_sidebar(st, DEFAULTS)
m = SimSirModel(p)

display_header(st, m, p)

if st.checkbox("Show more info about this tool"):
    notes = "The total size of the susceptible population will be the entire catchment area for Penn Medicine entities (HUP, PAH, PMC, CCH)"
    show_more_info_about_this_tool(st=st, model=m, parameters=p, defaults=DEFAULTS, notes=notes)

st.subheader("New Admissions")
st.markdown("Projected number of **daily** COVID-19 admissions at Penn hospitals")
admits_chart = build_admits_chart(alt=alt, admits_df=m.admits_df, max_y_axis=p.max_y_axis)
st.altair_chart(admits_chart, use_container_width=True)
st.markdown(chart_descriptions(admits_chart, p.labels))

if st.checkbox("Show Projected Admissions in tabular form"):
    admits_modulo = 1
    if not st.checkbox("Show Daily Counts"):
        admits_modulo = st.slider(
            label="Interval of Days",
            key="admissions_day_range_slider",
            min_value=1,
            max_value=10,
            value=7
        )
    table_df = build_admits_table(
        admits_df=m.admits_df,
        labels=p.labels,
        modulo=admits_modulo,
        as_date=p.as_date)
    st.table(table_df)
    display_download_link(st,
        filename="projected_admissions.csv",
        df=m.admits_df,
        parameters=p
    )


st.subheader("Admitted Patients (Census)")
st.markdown("Projected **census** of COVID-19 patients, accounting for arrivals and discharges at Penn hospitals")
census_chart = build_census_chart(alt=alt, census_df=m.census_df, max_y_axis=p.max_y_axis)
st.altair_chart(census_chart, use_container_width=True)
st.markdown(chart_descriptions(census_chart, p.labels, suffix=" Census"))

if st.checkbox("Show Projected Census in tabular form"):
    census_modulo = 1
    if not st.checkbox("Show Daily Census Counts"):
        census_modulo = st.slider(
            label='Interval of Days',
            key="census_day_range_slider",
            min_value=1,
            max_value=10,
            value=7
        )
    table_df = build_census_table(
        census_df=m.census_df,
        labels=p.labels,
        modulo=census_modulo,
        as_date=p.as_date)
    st.table(table_df)
    display_download_link(st,
        filename="projected_census.csv",
        df=m.census_df,
        parameters=p
    )

st.markdown(
    """**Click the checkbox below to view additional data generated by this simulation**"""
)
if st.checkbox("Show Additional Projections"):
    show_additional_projections(
        st, alt, additional_projections_chart, model=m, parameters=p
    )
    if st.checkbox("Show Raw SIR Simulation Data"):
        draw_raw_sir_simulation_table(st, model=m, parameters=p)
write_definitions(st)
write_footer(st)
